[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sherlog"
license = {text = "MIT"}
requires-python = ">=3.7"
version = "0.0.3"
dependencies = [
    "boto3",
    "tabulate"
]

[tool.setuptools]
package-dir = {"" = "source"}

[project.scripts]
sherlog = "main:main"